name: wigo_flutter
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  flutter_svg: ^2.2.0
  smooth_page_indicator: ^1.2.1
  country_code_picker: ^3.3.0
  dotted_border: ^2.1.0
  dio: ^5.9.0
  material_design_icons_flutter: ^7.0.7296
  flutter_gen: ^5.11.0
  intl: ^0.20.2
  google_maps_flutter: ^2.13.1
  file_picker: ^10.3.3
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  dropdown_button2: ^2.3.9





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^8.0.0
  mocktail: ^1.0.4
  flutter_gen_runner: ^5.11.0
  build_runner: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  assets:
    outputs:
      class_name: AppAssets

  integrations:
    flutter_svg: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
